### PR TITLE
add support for multiple owo-ui windows

### PR DESCRIPTION
**Pull request by BasiqueEvangelist**
Adds support for opening windows from the main Minecraft window through the `OwoWindow` class ~~(and the more bare bones `FramebufferWindow` class).~~

## Changes
- ~~`FramebufferWindow` allows creating a low-level separate window, with rendering fully managed by the user~~
- `OwoWindow` creates a window with an owo-ui component as the root, managing events and registering itself itself
- `WindowContext`/`CurrentWindowContext` allow detecting the current window and registering per-window features (which is useful for UI components that create window-sized framebuffers or screens)

### CODE REVIEW

**Comment by BasiqueEvangelist** [comment]
on 1.20.2 now

**Comment by Minenash** [comment]
Why was this closed?

**Comment by BasiqueEvangelist** [comment]
> Why was this closed?

I didn't want to continue maintaining a PR that didn't get any feedback after 1 month

**Comment by Minenash** [comment]
Yeah, that's fair. But damn, been looking forward to it since it was mentioned you were working on it

**Comment by BasiqueEvangelist** [comment]
> Yeah, that's fair. But damn, been looking forward to it since it was mentioned you were working on it

I can try to extract it into a separate library if you want to play around with it.
I will have to mixin into owo for that to work, though.

**Comment by BasiqueEvangelist** [comment]
Also, like, if there's *any* indication that this will be actually looked at (so that I won't have to bump the PR 6 times) I'll reopen this PR

**Comment by Minenash** [comment]
Yeah, if owo doesn't end up having it, then that would be awesome :heart:

**Comment by BasiqueEvangelist** [comment]
fuck it

**Pull request closed without merging**
