### PR TITLE
add support for exclusion areas in EMI

### PR DESCRIPTION
**Pull request by Abbie5**

### CODE REVIEW

**Comment by LemmaEOF** [comment]
Hey, is this gonna get merged any time soon? It's a *huge* hassle, especially as pack devs

**Review by gliscowo — APPROVED** [review]

**Comment by gliscowo** [comment]
While I do appreciate the thought, I do have to wonder whether this PR was actually, uh well, tested like at all?

The provided implementation doesn't work (in fact, can't work since EMI exlusion areas registered to a specific screen class only apply to screens of that specific class - not subclasses like is the case for REI) and needs to be replaced with a generic exclusion area which does the typecheck on its own

I have now implemented these changes and it does in fact work as expected

**Comment by Abbie5** [comment]
sorry about that, may i ask why the pr was merged rather than requesting changes though?

**Comment by gliscowo** [comment]
Well, I did not know about EMI's behavior on this function beforehand (since I am wholly unfamiliar with EMI) - I assumed this PR was properly tested and the actual logic of the code was perfectly fine

**Comment by Abbie5** [comment]
i see

**Pull request merged**
